apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: dexterquazi/nodedmall
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

