name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: npm run test 
      - name: build 
        run:  docker build -t dexterquazi/nodedmall . 
      - name: login
        run: cat pass | docker login docker.io --username dexterquazi --password-stdin && docker push dexterquazi/nodedmall && docker logout && cat k8s-1-28-2-do-0-nyc3-1705326191808-kubeconfig.yaml && mkdir ~/.kube && mv k8s-1-28-2-do-0-nyc3-1705326191808-kubeconfig.yaml ~/.kube/config &&KUBECONFIG=k8s-1-28-2-do-0-nyc3-1705326191808-kubeconfig.yaml  kubectl get all

