name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: npm run test && docker build -t dexterquazi/nodedmall .  && echo ${{ secrets.PASS }} | docker login docker.io --username dexterquazi --password-stdin && docker push dexterquazi/nodedmall && docker logout 
      - name: deploy
        run: echo ${{ secrets.PASS }}|base64 -d >/tmp/config && KUBECONFIG=/tmp/config && kubectl get all

