name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: npm run test && docker build -t dexterquazi/nodedmall .  && echo ${{ secrets.PASS }} | docker login docker.io --username dexterquazi --password-stdin && docker push dexterquazi/nodedmall && docker logout 
      - name: check
        run: kubectl -h
\     - name: cat
        run: cat k8s-1-28-2-do-0-nyc3-1705326191808-kubeconfig.yaml
      - name: deploy 
        run: kubectl apply -f deploy.yaml
