name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: test
        run: npm run test
      - name: build 
        run:  docker build -t dexterquazi/dmall . 
      - name: login
        run: cat pass | docker login docker.io --username dexterquazi --password-stdin && docker push dexterquazi/dmall
      - name: doctlget
        run: cd ~ && wget https://github.com/digitalocean/doctl/releases/download/v1.101.0/doctl-1.101.0-linux-amd64.tar.gz && tar xf ~/doctl-1.101.0-linux-amd64.tar.gz && sudo mv ~/doctl /usr/local/bin
      - name: doctlauth
        run: doctl auth init -t dop_v1_7f84778f9b09da723e9dad37e8422c7c534d2132140aa0f795211b875cc7ef09
