name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: test
        run: npm run test
      - name: build 
        run:  docker build -t dexterquazi/dmall . 
      - name: login
        run: echo ${{ secrets.PASS }}| docker login -u dexterquazi --password-stdin  && docker push dexterquazi/dmall
      - name: K8sAUTH
        run: doctl -h
